### ISSUE TITLE
get_message() sometimes missing close reason

### ISSUE THREAD

**Issue by pikeas** [HyperionGray/trio-websocket#158] opened 2021-05-21 21:58 UTC
```
while True:
    try:
        raw: str = await ws.get_message()
    except trio_websocket.ConnectionClosed:
        logger.info(f"Websocket closed: {ws.closed}")
        await trio.sleep(1)
        logger.info(f"Websocket closed: {ws.closed}")
```

```
[14:55:33] INFO:app:Websocket closed: None                                                                                                                     
[14:55:34] INFO:app:Websocket closed: CloseReason<code=1000, name=NORMAL_CLOSURE, reason=None> 
```

There appears to be some sort of race condition between closing the memory channel and setting `_close_reason`.

**Comment by belm0** [comment] 2021-05-22 00:42
Thank you for reporting.  Are you doing anything special on the other end to make this happen?

**Comment by belm0** [comment] 2021-05-22 00:45
It's concerning, since the code is often using `_close_reason` to determine whether the connection is closed.

```python
if self._close_reason:
    raise ConnectionClosed(self._close_reason)
```

**Comment by pikeas** [comment] 2021-05-22 00:53
> Thank you for reporting. Are you doing anything special on the other end to make this happen?

Nope, the other side is a 3rd party API. I have a) a receive task that consumes messages from the websocket and pushes them to my own MemoryReceiveChannel, b) a send task that pushes out messages with `await ws.send_message(ujson.dumps({...}))`, and c) a heartbeat task that ping/sleeps.

Here's my receive function in full:

```
async def receive(self):
    async with self.channel_tx:
        # TODO: consider async for raw in self.ws._recv_channel ?
        while True:
            try:
                raw: str = await self.ws.get_message()
            except trio_websocket.ConnectionClosed:
                await trio.sleep(1) # https://github.com/HyperionGray/trio-websocket/issues/158
                logger.info(f"Websocket closed: {self.ws.closed}")
                break
            message = parse_message(raw)
            if isinstance(message, dict):
                logger.info(f"Skipping message: {message}")
            else:
                await self.channel_tx.send(message)
```

**Comment by belm0** [comment] 2021-05-22 00:54
Perhaps it's happening in this path, where there is a context switch (`sleep(0)`) as well as blocking send in the REMOTE_CLOSING case, that delay setting the close reason via `_close_web_socket()`.

https://github.com/HyperionGray/trio-websocket/blob/15c64e8193270208f1f5b0eb475efe3abbb99f32/trio_websocket/_impl.py#L1085-L1095

I may not have time to debug it for a while-- help appreciated.

**Comment by belm0** [comment] 2021-05-22 01:03
I think you can confirm the problem source by instrumenting trio-websocket as follows, and run your sleep(1) example.

```python
async def _handle_close_connection_event(self, event):
    self._for_testing_peer_closed_connection.set()
    print('_handle_close_connection_event() sleep')
    await trio.sleep(0)
    if self._wsproto.state == ConnectionState.REMOTE_CLOSING:
        print('_handle_close_connection_event() send response')
        await self._send(event.response())
    print('_handle_close_connection_event() set reason')
    await self._close_web_socket(event.code, event.reason or None)
```

**Comment by belm0** [comment] 2021-05-22 11:27
the example client has this exception after executing the `close` command

perhaps this bug is a regression from a relatively recent change

```
cmd> close
DEBUG:trio-websocket:client-0 sending 8 bytes
DEBUG:trio-websocket:client-0 websocket closed ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>
DEBUG:trio-websocket:client-0 reader task finished
Traceback (most recent call last):
  File "client.py", line 72, in handle_connection
    nursery.start_soon(get_messages, ws)
  File "/.../site-packages/trio/_core/_run.py", line 815, in __aexit__
    raise combined_error_from_nursery
  File "client.py", line 130, in get_messages
    message = await ws.get_message()
  File "/.../trio_websocket/_impl.py", line 873, in get_message
    raise ConnectionClosed(self._close_reason) from None
trio_websocket._impl.ConnectionClosed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "client.py", line 136, in <module>
    if not trio.run(main, parse_args()):
  File "/.../site-packages/trio/_core/_run.py", line 1928, in run
    raise runner.main_task_outcome.error
  File "client.py", line 58, in main
    await handle_connection(conn, args.heartbeat)
  File "client.py", line 74, in handle_connection
    reason = '<no reason>' if cc.reason.reason is None else '"{}"'.format(
AttributeError: 'NoneType' object has no attribute 'reason'
```

**Comment by belm0** [comment] 2021-05-22 11:52
The problem seems to have been introduced way back in #79 ("Delay connection closed")

**Comment by pikeas** [comment] 2021-05-22 18:28
Instrumenting my client:

```
[22:40:43] INFO:app.ws:Websocket closed: None
[22:40:44] INFO:app:_close
           INFO:app:_close after sleep
           INFO:app:_close after send
           INFO:app:_close after _close_web_socket
           INFO:app.ws:Websocket closed: CloseReason<code=1000, name=NORMAL_CLOSURE, reason=None>
```

**Comment by belm0** [comment] 2021-05-22 22:40
So the problem is happening prior to the close connection handler-- that's helpful, thank you.

**Comment by belm0** [comment] 2021-05-23 06:12
Pending PR #159 fixes the case in the example client `close` command, but probably not the original report here.

@pikeas in your example would you print the `ConnectionClosed` exception?  Because the exception itself also holds `reason`, and I'm wondering if that is populated even though the websocket `closed` property isn't.

**Comment by belm0** [comment] 2021-05-23 06:18
Also, I may have missed it, but would you clarify which side is closing the connection in your case?

**Comment by pikeas** [comment] 2021-05-23 19:30
> @pikeas in your example would you print the `ConnectionClosed` exception? Because the exception itself also holds `reason`, and I'm wondering if that is populated even though the websocket `closed` property isn't.

Reason is `None` on the exception.



> Also, I may have missed it, but would you clarify which side is closing the connection in your case?

I'm calling `await ws.aclose()`.

Hope this helps, I'll try the PR when it lands!

**Comment by pikeas** [comment] 2021-05-23 19:41
Also, `ConnectionClosed` is instantiated as `ConnectionClosed(self._close_reason)`, so when `_close_reason` is None, printing the exception (rather than the `repr`) displays a blank string.

**Comment by belm0** [comment] 2021-05-24 00:14
> I'm calling `await ws.aclose()`.
> 
> Hope this helps, I'll try the PR when it lands!

oh, if you're calling `aclose()` on the side having the missing reason, then the pending PR may fix it

perhaps you could confirm the fix by installing it from source:
```
git clone -b close_reason_race https://github.com/HyperionGray/trio-websocket.git
cd trio-websocket/
pip install -e .
```

**Comment by pikeas** [comment] 2021-05-27 17:10
Confirmed, with the new branch I'm seeing `CloseReason<code=1000, name=NORMAL_CLOSURE, reason=None>` when catching `trio_websocket.ConnectionClosed`.

**Comment by belm0** [comment] 2021-05-27 21:30
Thank you for confirming.  Please give me some time to write tests, merge, and release.

I'm still concerned about a possible regression, since internally the code often uses `_close_reason` to signal being in connection closed state.

**Comment by belm0** [comment] 2023-03-19 10:44
the scope of the bug is wider than just the `closed` attribute being set incorrectly

this will cause `send_message()` during the close handshake to silently be ignored (it should raise `ConnectionClosed`), and for wsproto > 0.2.0 the `LocalProtocolError` will be leaked.

**Closed** 2023-03-19 11:11 UTC
Labels: bug
